### ISSUE TITLE
[Bug]: `herd.yml` Unable to install mysql: Name Mysql (8.0.36) is already in use.

### ISSUE THREAD

**Issue by wpalani** [beyondcode/herd-community#1093]
### Platform

macOS

### Operating system version

14.7 (23H124)

### System architecture

Intel (x86)

### Herd Version

Herd 1.11.1 (PRO)

### PHP Version

PHP 8.3

### Bug description

When having multiple projects that use `herd.yml`, running `herd init` returns the following errors
```
 ERROR  Unable to install mysql.
 ERROR  Name Mysql (8.0.36) is already in use.
```

here's my `herd.yml`
```yml
name: herd-website
php: '8.3'
secured: true
services:
    mysql:
        version: 8.0.36
        port: '${DB_PORT}'
    redis:
        version: 7.0.0
        port: '${REDIS_PORT}'
```

So, if I have project A that needs a MySQL service and it's present in the `herd.yml` file it will take the "Mysql" namespace in the services.

Then, when project B also needs MySQL service (let's say on a different port), it will return the error.

A way to solve this would be to provide the option to pass a name (just like the UI), like so:

```yml
name: herd-website
php: '8.3'
secured: true
services:
    MySQL:
        name: project_b_mysql
        version: 8.0.36
        port: '${DB_PORT}'
    redis:
        version: 7.0.0
        port: '${REDIS_PORT}'
```

If there's a way to solve this without doing it in the UI as of now that I missed, please let me know.
